name:    demo-emacs-haskell
github:  cydparser/demo-emacs-haskell

dependencies:
  - base >= 4.7 && < 5

default-extensions:
  - NoMonomorphismRestriction

ghc-options:
  - -Wall
  - -Wno-missing-signatures
  - -Wno-type-defaults
  - -Wno-unused-do-bind
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N

executables:
  demo-list:
    main: Main.hs
    source-dirs:
      - src

tests:
  doctest:
    main: DocTest.hs
    source-dirs:
      - test
    dependencies:
      - QuickCheck
      - doctest
  spec:
    main: Spec.hs
    source-dirs:
      - src
      - test
    dependencies:
      - QuickCheck
      - hspec
      - hspec-discover
